### PR TITLE
Use zend_call_function test

### PR DESCRIPTION
**Pull request by dreamsxin**

### CODE REVIEW

**Comment by sjinks** [comment]
Guys, as far as I can tell, this does not work. The issue is that sometimes `zephir_call_user_function` is called with `fn == NULL`, and the information about the called function is taken from `info` parameter.

I saw that when `zephir_throw_exception_format` called `__construct` method of the exception class: `fn` was `NULL`.

**Comment by sjinks** [comment]
I see that extended/fcall.h has a lot of code borrowed from Zend Engine. What I suggest is that we have a baseline version of execute methods that just works — my vision is that this version will just provide wrappers around `zend_call_function`. Once we have this working, we can try to optimize it.

And honestly, three years later I don't see a point in having our own replacement for `zend_call_function`: I don't think that `zend_call_function` is a real bottleneck, and any replacement becomes a nightmare to maintain in the long run.

@ovr @sergeyklay @dreamsxin

**Comment by dreamsxin** [comment]
@sjinks Why local , run `php tests/test2.php` it's fine, 

Evn:
`PHP 7.1.0 (cli) (built: Jan 20 2017 20:34:18) ( NTS )`

**Comment by Jurigag** [comment]
Dont merge it, i have fix without removing any zephir_ function calls, travis script looks like broken, like zephir copies new kernel files anyway.

**Comment by dreamsxin** [comment]
@Jurigag  I only test feasibility about `zend_call_function`, If ok, We can use `zend_fcall_info_cache` cache.

**Comment by Jurigag** [comment]
Just wait, i willl do pr to zephir repo.

**Comment by ovr** [comment]
@sjinks 

> And honestly, three years later I don't see a point in having our own replacement for zend_call_function: I don't think that zend_call_function is a real bottleneck, and any replacement becomes a nightmare to maintain in the long run.

Looks like you are right, main bad moment is that copying function like this way `zend_call_function` -> `zephir_call_function_opt` in `extends/fcall.c` is a bad idea

1. Anyone in feature cannot sync this code with original database to find what was changed
2. Possible Performance gain is not so fast

But droping "Global static cache " https://github.com/phalcon/zephir/pull/956 >= 7.1 looks like a bad idea refs

**Comment by dreamsxin** [comment]
Just do a little bit of adjustment to save the global static cache and need to generate key.

**Comment by sjinks** [comment]
@ovr `zend_call_function`accepts `zend_fcall_info_cache*` parameter which contains all necessary information about the scope of the function and its handler, I think it still can be used (we can use the current data structure to cache FCI, I think).

The issue is that there are cases when FCI should not be used (I am not sure if Zephir deals with them) — in this cases ZE explicitly de-initializes the cache passed to `zend_call_function` (ie, user function called via trampoline / tail recursion, functions called via magic handlers). I would prefer to rely upon ZE to handle such situations.

**Comment by sjinks** [comment]
That is, when we pass FCI cache to `zend_call_function` (and this is what PHP does when there is a call to a known function from the userland), `zend_is_callable_ex` is not invoked, and we have no performance penalty.

**Comment by sergeyklay** [comment]
@sjinks Well, I'm trying to sort out the way wich we shold follow. My, @dreamsxin  or @Jurigag's one. 
Right now we have a three bit different approaches

**Comment by Jurigag** [comment]
Well i mean if there is really no big performance impact on using zend_call_function then i really don't see any point using some zephir built-in - but first someone should just post some benchmark results from zephir and zend version.

**Comment by sjinks** [comment]
@Jurigag Zephir's version is a rewrite of Zend's `zend_call_function` and company.

For example, compare [zephir_is_callable_check_class](https://github.com/phalcon/zephir/blob/master/kernels/ZendEngine3/extended/fcall.c#L260) and [zend_is_callable_check_class](https://github.com/php/php-src/blob/master/Zend/zend_API.c#L2853), `zephir_is_callable_check_func` and `zend_is_callable_check_func`, `zephir_is_callable_ex` and `zend_is_callable_ex` etc

Back in 2013 (Phalcon), that made sense — PHP 5.3 had issues with closures, and we had a separate execute function for old PHP versions. Then, as PHP evolved, we had to backport fixes to it (for example, use locale-independent lowercase — since those times you can see `tolower_map` in fcall.c).

`phalcon_make_fcall_key` and `phalcon_fcall_populate_fci_cache` (they are `zephir_XXX` now) are since times when we discovered that PHP calls from userland are faster than Phalcon's (because PHP populates FCI at compile time, which is not possible at runtime). By the time PHP 5.6 was out, `phalcon_call_function` was basically a copy of `zend_call_function` with `#ifdef`s for different versions of PHP. In March 2014 I began to write code to eliminate `phalcon_call_function` in favor of `zend_call_function` but the subsequent events in Ukraine spoilt my plans.

Right now [zephir_call_function_opt](https://github.com/phalcon/zephir/blob/master/kernels/ZendEngine3/extended/fcall.c#L1032) is mostly a clone of [zend_call_function](https://github.com/php/php-src/blob/master/Zend/zend_execute_API.c#L678) with additional logic to handle `zephir_fcall_info*` parameter (and commented out logic that handles references, which can lead to unintended side effects).

**Comment by sjinks** [comment]
Looking into fcall logic, I feel that there is more than just one issue there… For example, `EG(fake_scope)` was meant to be used with object properties; `scope` in `zephir_is_callable_check_class` should be `zend_get_executed_scope()`, not `EG(fake_scope)`, etc…

**Comment by sergeyklay** [comment]
I'm closing this PR in favor of #6

**Pull request closed without merging**
