### PR TITLE
some change

### PR DESCRIPTION
**Pull request by Jurigag**

### CODE REVIEW

**Comment by Jurigag** [comment]
Seg fult with this change is fixed.

**Comment by Jurigag** [comment]
Only this happens right now:

```
	public static function call2()
	{
		return \Group\OoDynamicA::getNew();
	}
```

**Comment by Jurigag** [comment]
Well on travis there is some cache thing happening imho, i have it like this:

```
root@phalcon:~/issue1394# php tests/test1.php
Phpized
root@phalcon:~/issue1394# php tests/test2.php
stdClass
PHP Fatal error:  Uncaught RuntimeException: Call to undefined method self::getnew(), did you mean 'undefined'? in /root/issue1394/tests/test2.php:6
Stack trace:
#0 [internal function]: Group\OoDynamicA::call2()
#1 [internal function]: Group\OoDynamicA::call1()
#2 /root/issue1394/tests/test2.php(6): Group\Oo->testInstance12()
#3 {main}
  thrown in /root/issue1394/tests/test2.php on line 6
root@phalcon:~/issue1394# php -v
PHP 7.1.3-2+deb.sury.org~trusty+1 (cli) (built: Mar 15 2017 09:53:03) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.3-2+deb.sury.org~trusty+1, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.5.1, Copyright (c) 2002-2017, by Derick Rethans
```

**Comment by sergeyklay** [comment]
I'm closing this PR in favor of #6

**Pull request closed without merging**
